server:
  port: 8082

spring:
  application:
    name: so-manager-person
  datasource:
    url: jdbc:postgresql://localhost:5432/so
    username: esi
    password: esi
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka